module.exports = {
  ALGORITHM: 'HS256',
  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  JWT_ACCESS_EXPIRES_IN: 24 * 60 * 60, //24 hours
  JWT_REFRESH_EXPIRES_IN: 24 * 60 * 60,
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  secret: 'your secret key',
};
